<a href="https://colab.research.google.com/github/sebanie15/data_science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Norma wektora, długość wektora w R2

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

In [ ]:
### norma euklidesowav2 = np
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

### odległość dwuch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [ ]:
# odległość dwóch punktów w przestrzeni Rn

p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

In [4]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)


[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [8]:
z = np.dot(X, Y)
z


array([[ 2],
       [-6]])

In [9]:
z.shape

(2, 1)

In [10]:
x = np.array([[2, -1, 3],
              [3, 1, 0]])
y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(x, '\n')
print(y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [11]:
np.dot(x, y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### Wyznacznik macierzy

In [14]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10.0

### Ślad macierzy

In [16]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

### Macierz jednostkowa

In [17]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Macierz odwrotna

In [20]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [21]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

In [23]:
np.transpose(A) # lub np.T(A)

array([[ 2, -1],
       [ 4,  3]])

### Rozwiązywanie układów równań

In [24]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [25]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [26]:
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, B)
x

array([[1.],
       [2.]])

In [27]:
x.shape

(2, 1)