<a href="https://colab.research.google.com/github/sebanie15/data_science-bootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

### podstawy


In [82]:
import numpy as np
np.__version__


'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help((np.array))

### 1D array

In [ ]:
x = np.array([1, 3])
x

In [ ]:
print(x)

In [ ]:
type(x)

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
x.size

In [ ]:
x.dtype

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

### 2D array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x.ndim


In [ ]:
x.shape

In [ ]:
x = np.array([[1, 2, 4],[4, 2, 1]])
print(x)

In [ ]:
x.shape

### 3D array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
       [4, 2, 1]]]
)
x

In [ ]:
x.ndim

In [ ]:
x.shape

### Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
#możemy określić jakiego typu dane chcemy przechowywać w tablicy
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
# możemy również przekazac inny typ zmiennych, jak np. liczby złożone
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
# wpudowane typy danych z biblioteki numpy
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

In [ ]:
# wpudowane typy danych z biblioteki numpy
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

### Tworzenie tablic


In [ ]:
np.zeros(shape=((4, 10))) #domyslny typ danych to float

In [ ]:
np.zeros(shape=((4, 10)), dtype='int')

In [ ]:
np.ones(shape=(5, 5))

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

In [ ]:
np.arange(10) # równoznaczne do zapisu list(range(10)) tylko z biblioteki numpy

In [ ]:
np.arange(start=5, stop=10)

In [ ]:
np.arange(start=10, stop=100, step=10)

In [ ]:
np.arange(start=0, stop=1, step=0.05)

In [ ]:
np.linspace(start=0, stop=1, num=11)

In [ ]:
A = np.arange(15)
A

In [ ]:
A.reshape((3, 5))

In [ ]:
A.reshape((3, -1)) # -1 oznacza, ze python sam dobierze liczbe w zależności od ilości elementów

### Podstawowe operacje na tablicach


In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [ ]:
A + B # dodawanie element po elemencie, równierz inne operacje matematyczne

In [ ]:
A + 3 # dodaje 3 do każdego elementu

In [ ]:
np.add(A, B) # suma dwuch tablic

In [ ]:
np.subtract(A, B)

In [ ]:
np.multiply(A, B)

In [ ]:
np.divide(A, B)

In [ ]:
#mnożenie macierzowe

X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [ ]:
#mnożenie standardowe
print(X, '\n')
print(Y)
X * Y

In [ ]:
#mnożenie macierzowe

np.dot(X, Y)

In [ ]:
X.dot(Y) # mnożenie macierzy

In [ ]:
# mnożenie macierzy nie jest przemienne

Y.dot(X)

In [ ]:
X @ Y 3 inny zapis mnożenia macierzy

### generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
# rozkład jednostajny na przedziale
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

40

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([34, 12, 13, 23, 50, 82, 29, 82, 36, 76])

In [ ]:
np.random.choice([4, 2, 1, 3, 5])

3

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [86]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:

np.random.shuffle(data)
data

array([4, 6, 3, 5, 9, 2, 1, 0, 8, 7])

### podstawowe funkcje

In [88]:
np.exp(1)

2.718281828459045

In [89]:
np.sqrt(9)

3.0

In [90]:
np.all([2, 3, 1])

True

In [91]:
np.any([1, 2, 1]) # sprawdza czy którykolwiek wartośc zwraca true

True

In [97]:
A = np.random.rand(5)
A

array([0.44792617, 0.09956909, 0.35231166, 0.46924917, 0.84114013])

In [98]:
np.argmax(A)

4

In [99]:
A[np.argmax(A)]

0.8411401297855995

In [100]:
A[np.argmin(A)]

0.09956908911081108

In [101]:
np.argsort(A)

array([1, 2, 0, 3, 4])

In [102]:
np.max(A)

0.8411401297855995

In [103]:
np.mean(A)

0.44203924519158316

In [104]:
# mediana

np.median(A) 

0.4479261718707299

In [105]:
# odchylenie standardowe

np.std(A)

0.2389114477581765